teleop_twist_joy_node:
  ros__parameters:
    axis_linear:  # Left thumb stick vertical
      x: 1
      y: 0
    scale_linear:
      x: 0.4
      y: 0.4

    axis_angular:  # Left thumbstick horizontal
      yaw: 3
    scale_angular:
      yaw: 0.8
    require_enable_button: False

# docs:
# https://index.ros.org/p/teleop_twist_joy/github-ros2-teleop_twist_joy/#humble
 
