urg_node:
  ros__parameters:
    angle_min: -1.57
    angle_max: 1.57 # TODO: check this value we can prob see more than 90 degrees
    cluster: 1
    skip: 0
    frame_id: "laser"
    time_offset: 0.0
    serial_port: "/dev/ttyACM0"
    serial_baud: 115200
    ethernet_address: ""
    ethernet_port: 10940
    calibration: false
    publish_intensity: false