name: check-compile

on:
  push:
    branches:
      - main
      - fix/ci/ros2
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ros:iron-ros-base
    steps:
      - uses: actions/checkout@v2
      - name: build
        shell: bash
        run: |
          source /opt/ros/iron/setup.bash
          cd $GITHUB_WORKSPACE
          ls
          colcon build
