name: check-compile

on:
  push:
    branches:
      - main
      - feat/github-workflow
  pull_request:
    branches:
      - main
      - feat/github-workflow

jobs:
  build:
    runs-on: ros:noetic-ros-base

    steps:
      - name: Build workspace
        run: |
          source /opt/ros/noetic/setup.bash
          catkin build
