name: check-compile

on:
  push:
    branches:
      - main
      - feat/github-workflow
  pull_request:
    branches:
      - main
      - feat/github-workflow

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ros:noetic-ros-core
    steps:
      - name: build
        shell: bash
        run: |
          source /opt/ros/noetic/setup.bash
          apt-get update
          apt-get install -y python3-catkin-tools
          ls /__w/cobot_drive/cobot_drive
