name: check-compile

on:
  push:
    branches:
      - main
      - feat/github-workflow
  pull_request:
    branches:
      - main
      - feat/github-workflow

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ros:noetic-ros-core
    steps:
      - name: build
        run: |
          /bin/bash -c "source /opt/ros/noetic/setup.bash && ls"
